---
- hosts: testserver
  become: yes

  vars_files:
    - test_server_cred.yml 

  vars:
    ansible_become_pass: '{{ testserver_password }}'

  tasks:
    - name: Check if Nginx and monit is running.
      uri:
        url: "http://127.0.0.1:80/"
        user: devops
        password: test
        force_basic_auth: yes

