# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1804"
  config.vm.box_check_update = false
  config.vm.hostname = "testserver"
  config.vm.define "testserver"
  config.vm.network "public_network", ip: "10.0.42.110", bridge: "enp3s0"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.name = "testserver"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "test_playbook.yml"
    ansible.ask_vault_pass = true
  end
end
