---
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'arm'
  armv6l: 'arm6vl'

# Minio binaries path
minio_server_bin: /usr/local/bin/minio
minio_client_bin: /usr/local/bin/mc

# Runtime user and group for the Minio server service
minio_user: minio

minio_group: minio

minio_server_make_datadirs: true

# Switches to enable/disable the Minio server and/or Minio client installation.
minio_install_server: true
minio_install_client: false

# Minio access and secret keys
minio_access_key: "minio"
minio_secret_key: "miniotest"


minio_instances:
 - name: first
   minio_server_addr: ":9091"
   minio_server_datadirs: '/minio-data'
   minio_server_cluster_nodes:
    - 'http://10.42.0.25/minio-data'
    - 'http://10.42.0.26/minio-data'
    - 'http://10.42.0.27/minio-data'
    - 'http://10.42.0.28/minio-data'
    - 'http://10.42.0.29/minio-data'
    - 'http://10.42.0.30/minio-data'
   minio_server_envfile: /etc/default/minio1
   minio_service: "/etc/systemd/system/minio1.service"
   minio_service_name: minio1
 - name: second
   minio_server_addr: ":9092"
   minio_server_datadirs: '/minio-data2'
   minio_server_cluster_nodes:
    - 'http://10.42.0.25/minio-data2'
    - 'http://10.42.0.26/minio-data2'
    - 'http://10.42.0.27/minio-data2'
    - 'http://10.42.0.28/minio-data2'
    - 'http://10.42.0.29/minio-data2'
    - 'http://10.42.0.30/minio-data2'
   minio_server_envfile: /etc/default/minio2
   minio_service: "/etc/systemd/system/minio2.service"
   minio_service_name: minio2
