---
test_servers:
  hosts:
    testserver:
      ansible_host: 10.0.42.110
      #ansible_user: testadmin
      #ansible_ssh_private_key_file: ~/.ssh/dep7server_m
      ansible_python_interpreter: /usr/bin/python3