---
- name: Add the user
  user:
    name: '{{ username }}'
    shell: /bin/bash
    group: '{{ usergroup }}'
    append: yes
    password: "{{ upassword | password_hash('sha512') }}"
    update_password: on_create

- name: Limit serviceuser sudo rights to start|stop|restart services
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ username }} ALL=NOPASSWD:/bin/systemctl"
    validate: 'visudo -cf %s'
