# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.box_check_update = false
    config.vm.hostname = "proxyserver"
    config.vm.define "proxyserver"
    config.vm.network "public_network", ip: "10.42.0.110", bridge: "enp3s0"
    config.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "1024"
       vb.cpus=1
       vb.name = "proxyserver"
    end
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible_playbook/playbook.yml"
    end
  end