# -*- mode: ruby -*-
# vi: set ft=ruby :
$vm_num = 6
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.box_check_update = false
    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "512"
        vb.cpus=1
     end
     (1..$vm_num).each do |i|
        config.vm.define "node#{i}" do |node|
            node.vm.network "public_network", ip: "10.42.0.#{24+i}", bridge: "enp3s0"
            node.vm.hostname = "node#{i}"
            if i < 4
                node.vm.provision "ansible" do |ansible|
                    ansible.verbose = "v"
                    ansible.playbook = "playbook.yml"
                 end
            end
        end
    end
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "minio_playbook.yml"   
    end
end