# -*- mode: ruby -*-
# vi: set ft=ruby :
$vm_num = 6
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.box_check_update = false
    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "512"
        vb.cpus=1
     end
     (1..$vm_num).each do |i|
        config.vm.define "node#{i}" do |node|
            node.vm.network "public_network", ip: "192.168.1.#{24+i}", bridge: "enp3s0"
            node.vm.hostname = "node#{i}"
        end
    end   
    config.vm.provision "ansible" do |ansible|
       ansible.verbose = "v"
       ansible.playbook = "playbook.yml"
       ansible.limit = 'node1, node2, node3'
    end
end