---
test_server:
  hosts:
    testserver:
      ansible_host: 192.168.1.10
      ansible_user: testadmin
      ansible_ssh_private_key_file: ~/.ssh/dep7server_m
      ansible_python_interpreter: /usr/bin/python3